# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Account(object):
    def setupUi(self, Account):
        Account.setObjectName("Account")
        Account.resize(400, 300)
        self.uptLabel = QtWidgets.QLabel(parent=Account)
        self.uptLabel.setGeometry(QtCore.QRect(30, 20, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.uptLabel.setFont(font)
        self.uptLabel.setObjectName("uptLabel")
        self.ptoLabel = QtWidgets.QLabel(parent=Account)
        self.ptoLabel.setGeometry(QtCore.QRect(30, 60, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ptoLabel.setFont(font)
        self.ptoLabel.setObjectName("ptoLabel")
        self.vacationLabel = QtWidgets.QLabel(parent=Account)
        self.vacationLabel.setGeometry(QtCore.QRect(30, 110, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.vacationLabel.setFont(font)
        self.vacationLabel.setObjectName("vacationLabel")
        self.GoToShiftButton = QtWidgets.QPushButton(parent=Account)
        self.GoToShiftButton.setGeometry(QtCore.QRect(120, 160, 121, 81))
        self.GoToShiftButton.setObjectName("GoToShiftButton")

        self.retranslateUi(Account)
        QtCore.QMetaObject.connectSlotsByName(Account)

    def retranslateUi(self, Account):
        _translate = QtCore.QCoreApplication.translate
        Account.setWindowTitle(_translate("Account", "Account GUI"))
        self.uptLabel.setText(_translate("Account", "Available UPT: 0"))
        self.ptoLabel.setText(_translate("Account", "Available PTO: 0"))
        self.vacationLabel.setText(_translate("Account", "Available Vacation: 0"))
        self.GoToShiftButton.setText(_translate("Account", "Go to Shift"))
