# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(443, 300)
        self.label = QtWidgets.QLabel(parent=Main)
        self.label.setGeometry(QtCore.QRect(40, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Main)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Main)
        self.lineEdit.setGeometry(QtCore.QRect(150, 39, 251, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Main)
        self.lineEdit_2.setGeometry(QtCore.QRect(152, 90, 251, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Main)
        self.pushButton.setGeometry(QtCore.QRect(30, 150, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Main)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 150, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=Main)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Main)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 212, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Menu"))
        self.label.setText(_translate("Main", "Name"))
        self.label_2.setText(_translate("Main", "Password"))
        self.pushButton.setText(_translate("Main", "Register"))
        self.pushButton_2.setText(_translate("Main", "Login"))
        self.label_3.setText(_translate("Main", "Account: Not Logged In"))
        self.pushButton_3.setText(_translate("Main", "Enter"))
